### ISSUE TITLE
questions about the search and cache

### ISSUE THREAD

**Issue by marciogoularte** [YodasMyDad/ZauberCMS#37]
First of all, your project is fantastic. It's amazing to use Blazor in a CMS and with Umbraco concepts.

My questions are about the search. If the plan is to use Lucene .NET, the same as Umbraco. Also, if it would be to use Examine, like in Umbraco.
I want to contribute to the project and I have a lot of knowledge in this area.
Regarding caching, Umbraco has its own implementation, which would be NuCache. In the past, it was XML in memory. Is there any plan for something like that? I don't mean using XML, but some kind of local cache to avoid database calls.

**Comment by YodasMyDad** [comment]
Hi Marcio,

I have thought about Examine a few times. I'm not against it being added to the project, and I guess it would be useful as a search in the admin (and also for people wanting to add searching in the front end)

Caching: There is already a memory cache in place for content querying. I need to update this page below when v1 comes out so people know, and auto flushing when content is updated. I was thinking about adding it for media and users too.

https://aptitude.gitbook.io/zaubercms/creating-a-website/querying-data

Example of using it below, you just pass in Cached = true into the 

https://github.com/YodasMyDad/ZauberCMS/blob/master/ZauberCMS.Web/ContentViews/HomeView.razor#L66

**Comment by YodasMyDad** [comment]
I'm actually starting to think Examine is probably not the way to go now. Due to the file system issues Umbraco has, specifically with Azure and some other platforms. I need to have a think about it a bit more, most likely after v1
